# Generated by Django 4.2.6 on 2023-12-24 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_student_developer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='DOB',
        ),
    ]
