# Generated by Django 4.2.6 on 2024-01-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_developer_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=70)),
                ('contact', models.IntegerField()),
                ('domain', models.CharField(max_length=50)),
                ('resume', models.FileField(upload_to='Resume')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='developer',
            name='resume',
        ),
    ]
