# Generated by Django 4.2.6 on 2024-01-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_angular_aws_cplus_java_php_python'),
    ]

    operations = [
        migrations.CreateModel(
            name='hr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Comapny', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Contact', models.IntegerField()),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
    ]
