# Generated by Django 4.2.6 on 2024-01-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_hr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hr',
            old_name='Comapny',
            new_name='Company',
        ),
    ]
