# Generated by Django 4.2.6 on 2024-01-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_comapny_hr_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='mark',
            field=models.IntegerField(default=0),
        ),
    ]
