# Generated by Django 4.2.6 on 2024-02-20 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_domain_mark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='domain',
        ),
    ]
