# Generated by Django 4.2.6 on 2024-02-23 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_domain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='domain',
        ),
    ]
