# Generated by Django 4.2.6 on 2024-02-24 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_domain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='domain',
        ),
    ]
