# Generated by Django 4.2.6 on 2024-02-26 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_domain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='developer',
        ),
        migrations.DeleteModel(
            name='domain',
        ),
    ]
