# Generated by Django 4.2.6 on 2024-02-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_delete_developer_delete_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('education', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('pyear', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=70)),
                ('contact', models.IntegerField()),
                ('domain', models.CharField(max_length=50)),
                ('resume', models.FileField(upload_to='Resume')),
                ('mark', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
