# Generated by Django 4.2.6 on 2024-02-27 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_developer_domain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='developer',
        ),
    ]
