# Generated by Django 4.2.6 on 2024-03-01 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_category_question_alter_answer_qans_alter_answer_qid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='qid',
        ),
    ]
