# Generated by Django 4.2.6 on 2024-03-04 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_answer_qid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='answer',
        ),
    ]
