# Generated by Django 4.2.6 on 2024-03-04 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='answer',
        ),
    ]
