# Generated by Django 4.2.6 on 2024-03-04 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='answer',
        ),
    ]
