# Generated by Django 4.2.6 on 2024-06-18 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='developer',
        ),
        migrations.DeleteModel(
            name='domain',
        ),
    ]
