# Generated by Django 4.2.6 on 2024-06-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_developer_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='resume',
        ),
        migrations.AlterField(
            model_name='domain',
            name='resume',
            field=models.FileField(upload_to='Current_Resume'),
        ),
    ]
