# Generated by Django 4.2.6 on 2024-07-19 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_remove_developer_resume_alter_domain_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='developer',
        ),
        migrations.DeleteModel(
            name='domain',
        ),
    ]
