# Generated by Django 4.2.6 on 2024-07-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_developer_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='answer',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='developer',
            name='security',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
