# Generated by Django 4.2.6 on 2024-07-23 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_developer_answer_developer_security'),
    ]

    operations = [
        migrations.DeleteModel(
            name='developer',
        ),
        migrations.DeleteModel(
            name='domain',
        ),
    ]
