# Generated by Django 5.1.4 on 2025-02-13 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_developer_domain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='domain',
        ),
    ]
