# Generated by Django 5.1.4 on 2025-02-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_delete_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=70)),
                ('contact', models.IntegerField()),
                ('domain', models.CharField(max_length=50)),
                ('resume', models.FileField(upload_to='')),
                ('mark', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
