# Generated by Django 5.1.4 on 2025-02-16 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_domain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='angular',
        ),
        migrations.DeleteModel(
            name='answer',
        ),
        migrations.DeleteModel(
            name='aws',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='cplus',
        ),
        migrations.DeleteModel(
            name='developer',
        ),
        migrations.DeleteModel(
            name='domain',
        ),
        migrations.DeleteModel(
            name='hr',
        ),
        migrations.DeleteModel(
            name='java',
        ),
        migrations.DeleteModel(
            name='php',
        ),
        migrations.DeleteModel(
            name='python',
        ),
        migrations.DeleteModel(
            name='question',
        ),
    ]
