# Generated by Django 5.1.4 on 2025-02-16 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='developer',
        ),
    ]
