# Generated by Django 5.1.4 on 2025-02-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_delete_developer'),
    ]

    operations = [
        migrations.CreateModel(
            name='developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('education', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('pyear', models.IntegerField()),
                ('security', models.CharField(default=' ', max_length=1000)),
                ('answer', models.CharField(default=' ', max_length=500)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
