# Generated by Django 5.1.4 on 2025-03-10 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_developer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='domain',
        ),
    ]
