# Generated by Django 5.1.4 on 2025-03-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=100)),
                ('Pass', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='domain',
            name='resume',
            field=models.FileField(upload_to='Resume'),
        ),
    ]
