# Generated by Django 5.1.4 on 2025-03-12 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_admin_alter_domain_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
