# Generated by Django 5.1.4 on 2025-03-16 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='developer',
        ),
    ]
