# Generated by Django 5.1.4 on 2025-03-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_delete_developer'),
    ]

    operations = [
        migrations.CreateModel(
            name='developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('skill', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('github', models.CharField(max_length=50)),
                ('portfolio', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('graduationpy', models.IntegerField()),
                ('contact', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
