# Generated by Django 5.1.4 on 2025-03-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_developer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
