# Generated by Django 5.1.4 on 2025-03-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_delete_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Pass', models.CharField(max_length=100)),
                ('Role', models.CharField(max_length=100)),
                ('Contact', models.IntegerField()),
            ],
        ),
    ]
