# Generated by Django 5.1.4 on 2025-03-17 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='Pass',
            new_name='Password',
        ),
    ]
