# Generated by Django 5.1.4 on 2025-04-03 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_rename_pass_admin_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hr',
        ),
    ]
