# Generated by Django 5.1.4 on 2025-04-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_delete_hr'),
    ]

    operations = [
        migrations.CreateModel(
            name='hr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Company', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Contact', models.IntegerField()),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
    ]
