# Generated by Django 5.1.4 on 2025-04-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
